[package]
name = "joshuto"
version = "0.2.0"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]

[dependencies]
libc = "0.2.42"
serde = "1.0.70"
serde_derive = "1.0.70"
toml = "0.4"
tree_magic = "0.2.0"
whoami = "0.2.2"
xdg = "2.1.0"

[dependencies.ncurses]
version = "5.93.0"
features = [ "extended_colors" ]

[features]
default = []
