[package]
name = "joshuto"
version = "0.4.0"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
description = "Terminal file manager inspired by ranger"
homepage = "https://github.com/kamiyaa/joshuto"
license = "LGPL-3"

[dependencies]
clap = "2.32.0"
fs_extra = "1.1.0"
libc = "0.2.45"
keycodes = "0.1.0"
serde = "1.0.82"
serde_derive = "1.0.82"
toml = "0.4.10"
tree_magic = "0.2.1"
wcwidth = "1.0.1"
whoami = "0.2.4"
xdg = "2.2.0"

[dependencies.ncurses]
version = "5.97.0"
features = [ "extended_colors", "panel" ]

[features]
default = []
