[package]
name = "joshuto"
version = "0.8.0"
authors = ["Jiayi Zhao <jeff.no.zhao@gmail.com>"]
description = "Terminal file manager inspired by ranger"
homepage = "https://github.com/kamiyaa/joshuto"
license = "LGPL-3"
edition = "2018"

[dependencies]
alphanumeric-sort = "^1"
chrono = "^0"
dirs = "^1"
fs_extra = "^1"
lazy_static = "^1"
libc = "^0.2"
notify = "^4"
open = "1.2.2"
rustyline = "^4.1"
serde = "^1"
serde_derive = "^1"
structopt = "0.2.14"
text_io = "^0"
toml = "^0"
unicode-width = "^0"
users = "^0"
whoami = "^0"
xdg = "^2"

# clap = "*"
# fs_extra = "*"
# lazy_static = "*"
# libc = "*"
# mime_guess = "1.8.6"
# serde = "*"
# serde_derive = "*"
# toml = "*"
# wcwidth = "*"
# whoami = "*"
# xdg = "*"

[dependencies.ncurses]
version = "5.99.0"
features = [ "extended_colors", "panel", "wide" ]

[dependencies.wordexp]
version = "^0"
git = "https://github.com/kamiyaa/wordexp-rs"
branch="dev"
# path = "lib/wordexp-rs"

[features]
default = []
