show_hidden = true
# sort_method options: size, natural, basename, atime, ctime, mtime, type, random
sort_method = "natural"

[mimetypes]
"application/x-matroska"    = "mpv"
"application/x-shellscript" = "nano"
"image/jpeg"                = "feh"
"image/png"                 = "feh"
"text/plain"                = "nano"
