# sort_type options: size, natural, basename, atime, ctime, mtime, type, random
## currently only supports: natural, mtime
sort_type = "natural"
sort_case_sensitive = false
sort_reverse = false
sort_directories_first = true

# show hidden files
show_hidden = false

show_prerview = true

# ratios for parent view, current view and preview
column_ratio = [1, 3, 4]

# does nothing so far
scroll_offset = 6
