[keymaps]
# backspace = 263

mapcommand = [
    { command = "new_tab", keys = [ 20 ] },
    { command = "new_tab", keys = [ 84 ] },
    { command = "close_tab", keys = [ 23 ] },
    { command = "close_tab", keys = [ 87 ] },
    { command = "close_tab", keys = [ 113 ] },
    { command = "force_quit", keys = [ 81 ] },
    { command = "reload_dir_list", keys = [ 82 ] },
    { command = "toggle_hidden", keys = [ 122, 104 ] },

    { command = "tab_switch", args = [ "1" ], keys = [ 9 ] },
    { command = "tab_switch", args = [ "-1" ], keys = [ 353 ] },

    { command = "bulk_rename", keys = [ 98, 98 ] },
    { command = "set_mode", keys = [ 45 ] },

    { command = "cursor_move_up", keys = [ 259 ] },
    { command = "cursor_move_up", keys = [ 107 ] },
    { command = "cursor_move_down", keys = [ 258 ] },
    { command = "cursor_move_down", keys = [ 106 ] },
    { command = "cursor_move_end", keys = [ 360 ] },
    { command = "cursor_move_end", keys = [ 71 ] },
    { command = "cursor_move_home", keys = [ 262 ] },
    { command = "cursor_move_home", keys = [ 103, 103 ] },
    { command = "cursor_move_page_down", keys = [ 338 ] },
    { command = "cursor_move_page_up", keys = [ 339 ] },

    { command = "open_file", keys = [ 261 ] },
    { command = "open_file", keys = [ 108 ] },
    { command = "open_file", keys = [ 10 ] },
    { command = "open_file_with", keys = [ 114 ] },

    { command = "cd", keys = [ 103, 104 ] },
    { command = "cd", args = [ ".." ], keys = [ 260 ] },
    { command = "cd", args = [ ".." ], keys = [ 104 ] },

    { command = "cut_files", keys = [ 100, 100 ] },
    { command = "copy_files", keys = [ 121, 121 ] },
    { command = "paste_files", keys = [ 112, 112 ] },
    { command = "paste_files", args = [ "--overwrite" ], keys = [ 112, 111 ] },
    { command = "delete_files", keys = [ 100, 68 ] },
    { command = "delete_files", keys = [ 330 ] },

    { command = "rename_append", keys = [ 97 ] },
    { command = "rename_prepend", keys = [ 65 ] },

    { command = "select_files", args = [ "--toggle" ], keys = [ 32 ] },
    { command = "select_files", args = [ "--toggle", "--all" ], keys = [ 116 ] },

    { command = "search_next", keys = [ 110 ] },
    { command = "search_prev", keys = [ 78 ] },

    { command = "console", keys = [ 59 ] },
    { command = "console", args = [ "mkdir " ], keys = [ 109, 107 ] },
    { command = "console", args = [ "rename " ], keys = [ 99, 119 ] },
    { command = "console", args = [ "search " ], keys = [ 47 ] },

    { command = "cd", args = [ "/" ], keys = [ 103, 104 ] },
    { command = "cd", args = [ "/etc" ], keys = [ 103, 101 ] },
    ]
