[keymaps]
Quit = [ ["q"] ]

MoveUp = [
	["UP"],
	["j"]
]
MoveDown = [
	["DOWN"],
	["h"]
]
ParentDirectory = [
	["LEFT"],
	["h"]
]
Open = [
	["RIGHT"],
	["ENTER"]
]

MoveHome = [
	["HOME"]
]
MoveEnd = [
	["END"]
]
MovePageUp = [
	["PPAGE"]
]
MovePageDown = [
	["NPAGE"]
]

DeleteFile = [
	["d", "D"],
	[ "DELETE" ]
]
CutFile = [
	[ "d", "d" ]
]
RenameFile = [
	[ "a" ]
]
CopyFile = [
	["y", "y"]
]

OpenWith = [
	[ "r" ]
]
ToggleHiddenFiles = [
	[ "z", "h" ],
	["H"]
]
