# specify which applications to use to open certain file types
[mimetypes]

[[mimetypes.text]]
program = "nano"

[[mimetypes.text]]
program = "gedit"

[[mimetypes.text]]
program = "bat"

[[mimetypes.audio]]
program = "mpv"

[[mimetypes.video]]
program = "mpv"
fork = true
silent = true

[[mimetypes.image]]
program = "qimgv"
fork = true
silent = true

[[mimetypes.image]]
program = "krita"
fork = true
silent = true


[extensions]

[[extensions.pdf]]
program = "evince"
fork = true
silent = true

[[extensions.7z]]
program = "file-roller"
fork = true
silent = true

[[extensions.odt]]
program = "libreoffice"
fork = true
silent = true

