# specify which applications to use to open certain file types
[mimetypes]

[[mimetypes.pdf]]
program = "evince"
exec_type = "forking"

[[mimetypes.7z]]
program = "file-roller"
exec_type = "forking"

[[mimetypes.jpg]]
program = "qimgv"
exec_type = "forking"
[[mimetypes.jpg]]
program = "krita"
exec_type = "forking"

[[mimetypes.png]]
program = "qimgv"
exec_type = "forking"
[[mimetypes.png]]
program = "krita"
exec_type = "forking"

# Audio
[[mimetypes.flac]]
program = "mpv"

[[mimetypes.wav]]
program = "mpv"

# Videos
[[mimetypes.mkv]]
program = "mpv"
exec_type = "forking"

[[mimetypes.mp4]]
program = "mpv"
exec_type = "forking"

[[mimetypes.webm]]
program = "mpv"
exec_type = "forking"

[[mimetypes.wmv]]
program = "mpv"
exec_type = "forking"

# text
[[mimetypes.c]]
program = "nano"
[[mimetypes.cpp]]
program = "nano"
[[mimetypes.py]]
program = "nano"
[[mimetypes.conf]]
program = "nano"
[[mimetypes.java]]
program = "nano"
[[mimetypes.html]]
program = "nano"
[[mimetypes.md]]
program = "nano"
[[mimetypes.rs]]
program = "nano"
[[mimetypes.toml]]
program = "nano"
[[mimetypes.xml]]
program = "nano"

[[mimetypes.txt]]
program = "nano"


[[mimetypes.odt]]
program = "libreoffice"
exec_type = "forking"

