# specify which applications to use to open certain file types
[mimetypes]
"application/x-7z-compressed" = [
	["file-roller"]
]

"application/x-shellscript" = [
	["nano"],
	["gedit"]
]

"audio/mpeg" = [
	["mpv"]
]

"image/jpeg" = [
	["qimgv"],
	["feh"]
]
"image/png" = [
	["qimgv"],
	["feh", "-F"]
]
"text/plain" = [
	["nano"]
]

"text/x-rust" = [
	["nano"]
]

"text/x-csrc" = [
	["nano"]
]

"text/x-markdown" = [
    ["nano"]
]

"text/x-toml" = [
    ["nano"]
]

"audio/x-wav" = [
	[ "mpv" ]
]
"video/mp4" = [
	["mpv"]
]
"video/webm" = [
	["mpv"]
]
"video/x-matroska" = [
	["mpv"]
]
