# specify which applications to use to open certain file types
[mimetype]

[[mimetype.text]]
program = "nano"

[[mimetype.text]]
program = "gedit"

[[mimetype.text]]
program = "bat"

[[mimetype.audio]]
program = "mpv"

[[mimetype.video]]
program = "mpv"
fork = true
silent = true

[[mimetype.image]]
program = "qimgv"
fork = true
silent = true

[[mimetype.image]]
program = "krita"
fork = true
silent = true


[extension]

[[extension.tex]]
program = "nano"
[[extension.tex]]
program = "pdflatex"

[[extension.pdf]]
program = "evince"
fork = true
silent = true

[[extension.7z]]
program = "file-roller"
fork = true
silent = true

[[extension.odt]]
program = "libreoffice"
fork = true
silent = true

[[extension.rar]]
program = "unrar"
args = [ "e" ]
